import { Label } from "@/components/ui/label"
import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'Privacy Policy - Nelion Care - Bringing the best Home Care to your home',
    description: 'We are a family run Homecare Service provider dedicated to delivery of expert and compassionate person centred care in the comfort of you own home in Derbyshire, Nottinghamshire, Staffordshire and neigbouring counties.',
}


const conditions = [
    {title:"How we use your information",description:"This security strategy lets you know what's in store when Nelion care UK gathers your own data. It applies to data we gather about: Guests to our sites Guests to our online entertainment channels Individuals who present their data to us by means of online contact structures, messages, web-based entertainment or eye to eye and phone discussions Individuals who utilise Comfortable administrations Work candidates and current and previous representatives Our protection strategy likewise subtleties: The outsider frameworks and suppliers we use. Objections or inquiries about our security strategy. Admittance to individual data. Revelation of individual data. Connections to different sites. Changes to this strategy. Organisation subtleties"},
    {title:"Visitors to our websites",description:"At the point when somebody visits www.nelioncare.co.uk and www.nelioncare.co.uk or any of our office sites (for example www.www.nelioncare.co.uk ), we utilise an outsider help, Google Examination, to gather standard web log data and subtleties of guest ways of behaving. We do this to figure out things, for example, the quantity of guests we get to different pieces of the site. This data is just handled in a manner which doesn't recognise anybody. We don't make, and don't permit Google to make, any endeavour to figure out the personalities of those meeting our site. If we would like to gather by and by recognisable data through our site, we will do this in a fair, straightforward way. We will clarify when we gather individual data and will make sense of how we expect to manage it."},
    {title:"Use of cookies by Neil care UK",description:"A 'treat' is a little text record which joins to your hard drive and from which it can store and at times track data on how you utilise a specific site. We might involve treats for regulatory purposes, for example, classifying traffic designs all through the site and to dole out a 'client ID' for this reason. Treats, without help from anyone else, can't be utilised to figure out the personality of any client. On the off chance that you have a client ID, this will consequently distinguish your PC to our server when you visit our site, however it won't recognise you. Except if you explicitly tell us, we won't ever know what your identity is, regardless of whether we relegate a treat to your PC. You might set your program to dismiss all treats consequently. It is likewise conceivable to set your program to tell you in the event that a treat has been shipped off you so you can, at your circumspection, acknowledge or dismiss that specific treat. In any case, kindly note that you will be unable to utilize the full assistance on our site or different sites without treats."},
    {title:"Website search engine",description:"Our site search inquiries and results are logged secretly to assist us with working on our site and search usefulness. No client explicit information is gathered by either Nelion care UK or any outsider."},
    {title:"Social Sharing",description:"On our site, we utilise social sharing buttons for administrations including, however not restricted to, Twitter, LinkedIn and Facebook. These permit you to share site pages with your companions by means of those organisations. While you will be asked to login to utilise these administrations, this interaction is dealt with straightforwardly with the interpersonal organisation suppliers and their data sets and waiters; Nelion care acknowledges no liability regarding any utilisation of your by and by recognisable data and additionally any further utilisation of treats by those informal community suppliers."},
    {title:"People who submit their information to us via online contact forms, emails, social media or face-to-face and telephone conversations",description:"Your own information will empower Comfortable UK to keep you refreshed with important data about our administrations. Our correspondences with you might be by means of post, phone or email, and may start from Comfortable UK or our provincial workplaces. We won't give your subtleties to outsiders for advertising. You will be qualified for quit getting a picked correspondence whenever, by following the withdraw headings gave (if proper) or by reaching info@nelioncare.co.uk"},
    {title:"People who contact us via online forms",description:"At the point when a guest presents an enquiry structure on our site, the structure will just expect you to enter data which is crucial with the end goal of the structure, to guarantee we can give you the planned reaction. At the point when a contact structure is presented, the site takes the data and results an email to the assigned email address for that enquiry. If it's not too much trouble, see 'Individuals who get in touch with us by means of email' for detail on how this information will be taken care of. The enquiry is additionally saved to the site's essential information base utilising the 'Flamingo' module. The information is held on the site for quite a long time before it is erased. This information can be gotten to by a confined group of staff individuals with their own login data."},
    {title:"People who contact us via email",description:"Our messages are upheld utilising secure, level 3 military grade server farms imitated around the country. The pertinent data will be taken from the email, utilised for its expected reason and put away safely. The email will then be erased. We will likewise screen any messages shipped of us, including record connections for infections or noxious programming. If it's not too much trouble, know that you have an obligation to guarantee that any email you send is inside the limits of the law."},
    {title:"People who contact us via social media",description:"If it's not too much trouble, know that: (a) our virtual entertainment channels are public and any commitment you cause will to be accessible for anybody to see; and (b) messages sent over the Web, means of versatile applications may not be totally secure as they are dependent upon conceivable capture attempt or misfortune or conceivable change. This isn't inside our control thus we are not liable for themselves and won't be obligated to you or any other person for any harms or generally regarding any message sent by you to us or any message sent by us to you over the Web or through a versatile application. We are continuously endeavouring to comprehend our clients better, so we may likewise record remarks and feelings that you make openly on our virtual entertainment channels. In the event that you send us a private or direct message by means of web-based entertainment the message will be put away by the online entertainment channel and Hoot-suite for a long time. It won't be imparted to some other associations. Any private information which you truly do give us is covered under our protection strategy."},
    {title:"People who make a complaint to us",description:"At the point when we get a protest from an individual we will make a document containing the subtleties of the grumbling. This typically contains the character of the complainant and some other people engaged with the objection. We will just utilise the individual data we gather to handle the grumbling and to keep an eye fair and square of administration we give. We truly do order and distribute measurements showing data like the quantity of protests we get, yet not in a structure which distinguishes anybody. We typically need to uncover the complainant's personality to whoever the protest is about. Here, for instance, the precision of an individual's record is in question. On the off chance that a complainant doesn't need data distinguishing the person in question to be unveiled, we will attempt to regard that. Nonetheless, it may not be imaginable to deal with a grievance on an unknown premise. We will keep individual data contained in protest documents in accordance with our maintenance strategy. This implies that data connecting with a protest will be held for a considerable length of time from conclusion. It will be held in a protected climate and admittance to it will be confined by the 'need to know' standard. Likewise, where enquiries are submitted to us we will just utilise the data provided to us to manage the enquiry and any resulting issues and to beware of the degree of administration we give. Normally we distinguish no complainants except if the subtleties have proactively been disclosed."},
    {title:"People who use Neilon care UK services",description:"Comfortable UK overwhelmingly goes about as a Franchisor to an organisation of Home Consideration suppliers. We should hold the subtleties of individuals who enquire about our administrations to offer our types of assistance or the pertinent data. Be that as it may, we just utilise these subtleties to offer the support the individual has mentioned and for other firmly related purposes. For instance, we could utilise data about individuals who have mentioned to turn into a Comfortable UK Franchisee, to complete a study to see whether they are content with the degree of administration they got. We will regard your security and secrecy consistently and will continuously act as per this Protection Strategy while taking care of every single Individual Datum. As per the Information Security Regulation, we might involve your Own Information as vital for the arrangement of our administrations to you. We might utilise your Own Information with your assent, to reach out to you and proposition you different administrations that we think might bear some significance with you. We likewise may utilise your Own Information when it is to our greatest advantage for interior purposes related with keeping up with our business, to at last help in offering a viable assistance to you, and to advertise. We may likewise utilise your Own Information as legally necessary, for example, for charge purposes and to fulfil the administrative necessities of the Consideration Controller. We might reveal Individual Information (counting Delicate Individual Information) to outsiders in specific restricted conditions, in the event that we accept such revelation is to your greatest advantage; proper for the presentation of the Administrations; or is expected as an issue of regulation. Subtleties of your name, address and instalment record might be submitted to a credit reference organisation."},
    {title:"Job applicants, current and former Neilon care UK employees",description:"Comfortable UK is the information regulator for the data you give during the interaction except if generally expressed. In the event that you have any questions about the cycle or how we handle your data, if it's not too much trouble, get in touch with us at info@nelioncare.co.uk"},
    {title:"What will we do with the information you provide to us?",description:"All of the data you give during the cycle may be utilised to advance your employment form, or to satisfy lawful or administrative necessities if essential. We won't share any of the data you furnish during the enrolment interaction with any outsiders for the purpose of advertising and won't share any of your data beyond the European Financial Region. The data you give will be held safely by us or potentially our information processors, whether the data is in electronic or actual configuration. We will utilise the contact subtleties you give to us to reach you to advance your application. We will utilise the other data you give to evaluate your reasonableness to the job you have applied for."},
    {title:"What information do we ask for, and why?",description:"We don't gather more data than we really want to satisfy our expressed purposes and won't hold it for longer than is needed. The data we request is utilised to evaluate your appropriateness for business. You don't need to give what we ask to, however it could influence your application on the off chance that you don't."},
    {title:"Use of data processors",description:"Information processors are outsiders who give components of our enlistment administration for us. We have contracts set up with our information processors. This implies that they can do nothing with your own data except if we have taught them to make it happen. They won't impart your own data to any association separated from us. They will hold it safely and hold it for the period we train."},
    {title:"How long is the information retained for?",description:"In the event that you are fruitful, the data you give during the application cycle will be held by us as a component of your worker document for the span of your work in addition to 6 years following the finish of your business. This incorporates your crook records announcement, wellness to work, records of any security checks and references. Assuming you are fruitless at any phase of the interaction, the data you have given until that point will be held for quite a long time from the conclusion of the mission. Data produced all through the appraisal interaction, for instance interview notes, is held by us for quite a long time following the conclusion of the mission. Equivalent open doors data is held for a very long time following the conclusion of the mission regardless of whether you are effective."},
    {title:"Complaints or queries about our privacy policy",description:"Nelion care UK attempts to fulfil the most elevated guidelines while gathering and utilising individual data. Consequently, we take any protests we get about this truly. We urge individuals to draw it out into the open assuming they feel that our assortment or utilisation of data is unreasonable, deluding or unseemly. We would likewise invite any ideas for working on our systems. This protection notice was drafted considering quickness and lucidity. It doesn't give thorough detail of all parts of Nelion care UK's assortment and utilisation of individual data. Nonetheless, we are glad to give any extra data or clarification required. Any solicitations for this ought to be shipped off the location underneath."},
    {title:"Access to personal information",description:"Comfortable UK attempts to be really open as far as giving individuals admittance to their own data. People can see whether we hold any private data by making a 'subject access demand' (SAR). On the off chance that we in all actuality do hold data about you, we will: furnish you with a depiction of the data we hold; explain to you why we are holding it; let you know who it very well may be unveiled to; and give you have a duplicate of the data access a coherent structure. Anybody wishing to make a SAR to Comfortable UK for any private data, ought to do as such by carefully recording the solicitation to the location gave beneath. In the event that you concur, we will attempt to manage your solicitation casually, for instance, by furnishing you with the particular data you want via phone. Yet again assuming we really do hold data about you, you can request that we right any missteps by, reaching our information regulator at the location underneath."},
    {title:"Disclosure of personal information",description:"As a rule we won't uncover individual information without assent. Nonetheless, when we explore an objection, for instance, we should impart individual data to the association concerned and with other important bodies. You can likewise demand additional data on the accompanying, by keeping in touch with us at the location gave underneath: arrangements we have with different associations for sharing data; conditions where we can pass on private information without assent for instance, to forestall and recognize wrongdoing and to create anonymised measurements; our directions to staff on the best way to gather, use and erase individual information; and how we check that the data we hold is precise and state-of-the-art."},
]


export default function PrivacyPolicy() {
  return (
      <div className="flex pb-1 md:pb-8 w-full flex-col items-center justify-center space-y-2 md:space-y-8 bg-gradient-to-r from-fuchsia-200 via-violet-200 to-red-200">
          <div className="h-[150px] w-full flex flex-row items-center justify-center bg-[url('../../public/images/contact-bg.jpg')] bg-center bg-cover">
              <div className="w-full h-full bg-slate-500/50 flex flex-col justify-center items-center">
                  <Label className="text-4xl font-bold text-center text-white ">Privacy Policy</Label>
              </div>
          </div>
              <section className="prose prose-lg max-w-[800px] bg-white p-8 rounded-lg shadow-lg">
                  <h2 className="text-fuchsia-600 text-3xl font-semibold my-2">Introduction</h2>
                  <p>
                      Comfortable UK is focused on safeguarding the security of guests to our site,
                      endorsers of our pamphlets and those furnishing us with contact data. Kindly read
                      the accompanying Protection Strategy to comprehend how your own data is dealt
                      with. Now and again, Comfortable UK might offer new data or administrations that
                      might influence this arrangement. On the off chance that you have any various forms
                      of feedback with respect to this Security Strategy, kindly send an email to
                      info@nelioncare.co.uk
                  </p>
                  <h2 className="text-fuchsia-600 text-3xl font-semibold">Privacy Policy</h2>
                  {conditions.map((data,index)=>(
                      <div className="my-4" key={index}>
                          <h3 className="text-fuchsia-500 text-xl font-semibold">{data.title}</h3>
                          <p>
                              {data.description}
                          </p>
                      </div>
                  ))}
              </section>
      </div>
  )
}
