import { Label } from "@/components/ui/label"

const conditions = [
    {title:"Our Services",description:"NelionCare provides qualified home care for individuals with age-related or physical limitations. While our website offers details about our services and general information on home care, it&apos;s important to remember that this information is not a substitute for professional medical advice. Consulting with a qualified healthcare professional remains crucial for addressing your specific health needs or those of your loved ones. The information found here lacks the thorough assessment and evaluation that comes with a medical consultation. Therefore, it shouldn&apos;t be seen as a professional opinion or recommended course of action for your individual situation. Please keep this in mind when using the website and its content. This version uses simpler language, shorter sentences, and avoids unnecessary legal jargon. It also emphasizes the importance of seeking professional medical advice while clarifying the limitations of the website&apos;s information. I hope this is helpful! Let me know if you have any other questions."},
    {title:"Modifications to Terms of Use or The Website",description:"Comfortable stores the right, whenever, without notice, to change, adjust, update, or eliminate bits of the Terms of Purpose or The Site without responsibility to you or any outsider. If it's not too much trouble, really look at the Terms of Purpose every once in a while as your proceeded with utilisation of The Site means your acknowledgment of any changes, increments, or erasures."},
    {title:"Restrictions On Use of The Website and Its Contents",description:"The Site is claimed and worked by Nelion care UK. All data, archives and content showing up on The Site, including without restriction the text, site plan, logos, illustrations, symbols and pictures, brand names and administration stamps, and protected material, as well as the choice, gathering and course of action thereof, are the sole property of Nelion care UK. You consent to utilise the data, reports and content of The Site just for your own utilisation and for no other reason. Dependent upon the Terms of Purpose, Comfortable awards you a non-select, non- adaptable, restricted right to access, use and show The Site and the data, records and content on The Site. We approve you to download and print the data, content and records on The Site exclusively for your own, noncommercial review, perusing and shopping purposes. The authorisation of purpose conceded to you in the Terms of Purpose isn't an exchange of title and your utilisation is dependent upon the accompanying limitations: (1) some other duplicating, use, adjustment, multiplication, execution, show, joining into some other Site or other work, reflecting The Site, outlining The Site, or reallocation, retransmission or distribution of any downloaded material is completely denied without our express composed assent; (2) you make a deal to avoid changing or erase any copyright, brand name or other exclusive notification from any duplicate of the data, content and records which you download or print from The Site; (3) you make a deal to avoid interfering with or endeavour to interfere, in entire or to some degree, the tasks of The Site."},
    {title:"Rules of User Conduct",description:"By posting data in or in any case utilising any correspondences administration, discussion channel, message board, newsgroup, programming library or other intelligent help that might be accessible to you on or through The Site, you concur that you won't transfer, post or in any case circulate or work with dissemination of any happy, including without limit message, correspondences, programming, pictures, sounds, information or other data, that: is unlawful, undermining, oppressive, bugging, disparaging, derogatory, misleading, fake, obtrusive of another's protection, convoluted, contains unequivocal or realistic depictions or records of sexual demonstrations (counting yet not restricted to sexual language of a rough or compromising nature coordinated at one more individual or gathering of people) or in any case disregards the Terms of Purpose; deceives, badgers, corrupts or threatens an individual or gathering of people based on religion, orientation, sexual direction, race, identity, age or incapacity; encroaches on any patent, brand name, proprietary advantage, copyright, right of exposure or other exclusive right of our own or any outsider; comprises unapproved or spontaneous promoting, garbage or mass email (otherwise called \"spamming\"), junk letters, some other type of unapproved sales or any type of lottery or betting; contains programming infections or some other PC code, records or projects that are planned or expected to, or really do, disturb, harm or cutoff the working of any product, equipment or broadcast communications hardware or to harm or get unapproved admittance to any information or other data of any outsider; or on the other hand imitates any individual or substance, including any worker or agent of us. You concur that you won't abuse or manhandle account access and passwords, and that you are exclusively liable for all lead and transmissions that occur under your record access and passwords. Comfortable by and large doesn't pre-screen, screen or alter the substance posted by clients of correspondences administrations, discussion channels, message sheets, newsgroups, programming libraries or other intelligent administrations that might be accessible on or through The Site. In any case, we have the right at our only carefulness to eliminate any satisfied that, in our judgment, doesn't agree with the Terms of Purpose or is generally destructive, frightful or wrong. We are not answerable for any disappointment or postpone in eliminating such happy."},
    {title:"No Medical Advice or Recommendations",description:"The Site offers data, devices and assets to deal with the consideration of people with age-related and actually incapacitating necessities. Comfortable doesn't give clinical guidance through The Site or through any administrations presented on The Site. We are not a clinical reference administration and The Site doesn't give clinical references, or make proposals or supports for any medical care suppliers."},
    {title:"Disclaimers",description:"While Comfortable undertakings to give the most dependable, forward-thinking data accessible, the archives, content and data contained on The Site may, now and again, contain specialised mistakes, typographical blunders, and different mistakes or missteps and might be changed or refreshed without notice. We can't ensure or warrant that the substance or other data gave through The Site will be precise or modern or that the strategy for buying items and additionally administrations will work accurately. In the occasion any help or item is recorded at an erroneous value or isn't really accessible because of wrong provider data or other blunder, we will reserve the option to reject or drop orders set for the items or administrations recorded at the mistaken cost or truly inaccessible, whether or not your Visa has been charged and the request has been affirmed. Data on cost and accessibility is dependent upon future developments without notice. We are not liable for any help interferences on The Site or its accessibility to you. The Site and the data, content and records on The Site are given by us on an \"with no guarantees\" premise. Comfortable makes no portrayals or guarantees of any sort as for any of the items or administrations sold through The Site and thus disavow any inferred guarantees with respects thereto. We don't warrant the precision, fulfilment, cash or unwavering quality of any of the substance, data and records tracked down on The Site. You recognise that any dependence on any such happy, data and reports will be at your only gamble. To the full degree passable by material regulation, Comfortable disavows all portrayals and guarantees of any sort, express or suggested, including, yet not restricted to, inferred guarantees of merchantability and qualification for a specific reason, concerning the activity of The Site, and the data, content, and reports remembered for The Site and we renounce all portrayals and guarantees of any sort, express or inferred, with respect to title or responsibility for content, data and records on The Site."},
    {title:"Limitation of Liability",description:"Comfortable will not be at risk for any harms to or infections that might taint your PC hardware or programming by virtue of your utilisation of The Site. To the full degree admissible under relevant regulation, we will not be at risk to you or some other individual under any agreement, misdeed, severe obligation or other legitimate hypothesis for any harms of any sort connecting with the utilisation or endeavoured utilisation of The Site, its substance, data, archives or connections, including, yet not restricted to, extraordinary, excellent, circuitous, significant, coincidental, or correctional harms (counting yet not restricted to, lost benefits or lost reserve funds)."},
    {title:"Links",description:"The Site might contain connections to different Sites on the Web that are possessed and worked by outsider sellers and other outsiders. Comfortable is giving these connections exclusively as a comfort. The presence of a connection doesn't suggest our support of the connection or site, nor are we liable for the substance of any connected site. Joins don't suggest that we are subsidiary with or related with, or that we are legitimately approved to utilise, any brand name, or copyright or other respectability privileges showed in or open through the connections, or that any connected Site is approved to utilise any brand name, trademark, logo or copyright image of our own. You access connected Sites in spite of the obvious danger ahead and it is your obligation to go to all defensive lengths to make preparations for infections or other horrendous components or projects. All connects to The Site should be endorsed recorded as a hard copy by Nelion care, then again, actually we agree to joins which as it were: (1) connect by means of a text just connection containing the name Comfortable; (2) the connection focuses just to www.nelioncare.co.uk and not to more profound pages; (3) the connection, when enacted by a client, shows that page as a full-screen in a completely operable and traversable program window and not inside a \"outline\" on the connected Site; and (4) the connection and related data should not make the presence of any alliance among us and the Site offering the connection to The Site."},
    {title:"Third-Party Content",description:"Certain substance, data and reports from outsider merchants might be made accessible as a component of The Site. Nelion care doesn't support or ensure the exactness or fulfilment of this substance, data and archives and such satisfied, data and records are all the sole liability and risk of such outsider merchants."},
    {title:"Compliance With Laws",description:"You consent to conform to every material regulation, resolutions, laws and guidelines in regards to your utilisation of The Site and your acquisition of items or administrations through The Site. Nelion care may, in our only circumspection, report genuine or saw infringement of regulation to policing other fitting specialists. On the off chance that we become mindful, through a grumbling etc., of any potential or associated infringement with the Terms of Purpose, we may (however are not committed to) direct an examination to decide the nature and degree of the thought infringement and the fitting requirement activity, during which examination we might suspend administrations to any individual being researched and additionally eliminate any material from our servers. You consent to collaborate completely with any such examination. You recognise that infringement of the Terms of Purpose could expose you to criminal or common punishments."},
    {title:"User Responsibilities, Communications, Feedback, and Submissions",description:"By utilising The Site, you address that you are of adequate lawful age to involve The Site and to make restricting legitimate commitments for any risk you might cause because of your utilisation of The Site. You make a deal to avoid utilising The Site or any satisfied, data and reports contained on it for any unlawful or unseemly exercises. Nelion care invites your remarks and input with respect to The Site. All remarks, criticism, thoughts, ideas and other comparative entries revealed, submitted or proposed to us while utilizing The Site etc.( (by and large, \"Entries\") are not classified and will become and remain our property. We will be qualified for use, show, distribute, recreate, alter, communicate, sublicense, decipher and make subordinate works from and disperse these Entries in any medium and through a strategy for circulation, transmission or show for any reason at all, business etc., without pay or some other commitment to the supplier of the Entries."},
    {title:"Collection of Information",description:"Any actually recognisable data you might give to Nelion care through The Site is safeguarded exclusively by the Terms of Purpose. You thusly concur that data you ship off us through The Site, whether your data or data you are sending for another person's sake, can't be ensured to remain altogether private and that we might involve such data in congruity with the Terms of Purpose. By giving us data through The Site, you are concurring that we might utilise any thoughts, ideas, skill or other data you give to us by means of The Site. You warrant that you won't give any data or materials to us by means of The Site that is slanderous, compromising, disgusting, pestering, or generally unlawful, or that consolidates restrictive or classified data or yours or of others."},
    {title:"Termination of Usage",description:"Nelion care UK might end or suspend your admittance to all or part of The Site, without notice, for any lead that we, in our only attentiveness, accept is problematic to The Site or is disregarding any pertinent regulation or the Terms of Purpose."},
    {title:"Applicable Law",description:"Nelion care UK controls The Site from our workplaces in Merseyside, Joined Realm. The regulations pertinent to the understanding of these Terms of Purpose will be the laws of the Assembled Realm. Assuming that any arrangement inside these Terms of Purpose is held to be invalid or unenforceable, such arrangement will be struck and all excess arrangements will be implemented."},
    {title:"Indemnification",description:"You consent to guard and repay Comfortable from and against any case, reason for activity or interest, including without impediment sensible legitimate and bookkeeping charges, brought against us because of your improper utilisation of The Site or your utilisation of The Site infringing upon the Agreements."},
    {title:"Disputes",description:"No activity emerging under or connecting with the Terms of Purpose or The Site might be brought by either party over one year after the reason for activity has accumulated."},
    {title:"Notices",description:"\"Comfortable\", \"Right Consideration\" and \"Dementia Deferral\" are our brand names as well as administration marks. Every single such brand name, trademarks and administration marks are restrictive to us, and may not be utilised regarding any item or administration that isn't our own, in any way that is probably going to create turmoil among clients or in any way that trashes or dishonours us, without our composed authorisation. Any remaining brand names, item names and company names and logos are the property of their particular proprietors."},
]


export default function TermsAndConditions() {
  return (
      <div className="flex pb-1 md:pb-8 w-full flex-col items-center justify-center space-y-2 md:space-y-8 bg-gradient-to-r from-fuchsia-200 via-violet-200 to-red-200">
          <div className="h-[150px] w-full flex flex-row items-center justify-center bg-[url('../../public/images/contact-bg.jpg')] bg-center bg-cover">
              <div className="w-full h-full bg-slate-500/50 flex flex-col justify-center items-center">
                  <Label className="text-4xl font-bold text-center text-white ">Terms & Conditions</Label>
              </div>
          </div>
          <section className="prose prose-lg max-w-[800px] bg-white p-8 rounded-lg shadow-lg">
              <h2 className="text-fuchsia-600 text-3xl font-semibold my-2">Introduction</h2>
              <p>
                  When you visit or interact with any of our websites, including www.nelioncare.co.uk and others operated by NelionCare, Inc. (collectively referred to as &quot;The Website&quot;), you are agreeing to comply with the terms, conditions, policies, and other obligations outlined in this document and those found in our privacy policies and other policies accessible on The Website (collectively referred to as the &quot;Terms of Use&quot;). If you do not fully agree with the Terms of Use, please refrain from using The Website.
                  It&apos;s important to note that the Terms of Use specifically address your use of The Website and the information, documents, and content found within it. Separate terms and conditions may apply to products and services offered by us through The Website or through other means. These Terms of Use constitute the complete and binding agreement between you and us regarding your use of The Website.
              </p>
              <h2 className="text-fuchsia-600 text-3xl font-semibold">Terms of Service</h2>
              {conditions.map((data,index)=>(
                  <div className="my-4" key={index}>
                      <h3 className="text-fuchsia-500 text-xl font-semibold">{data.title}</h3>
                      <p>
                          {data.description}
                      </p>
                  </div>
              ))}
          </section>
      </div>
  )
}
